---
title: 'Principles of Orchestration: Summary of Aesthetics'
author: Adam Sadowski
date: '2018-06-17'
slug: principles-of-orchestration:-a-summary-of-aesthetics
categories:
  - Music
tags:
  - Orchestration
---

Below is a summary of aesthetics discussed in Korsakov's [Principles of Orchestration](http://www.gutenberg.org/files/33900/33900-h/33900-h.htm).

-	Strings are the most expressive melodic and harmonic instruments with a plethora of bowing methods
    +	In order, violin is more expressive than viola and etc.
    + Outside the range of human voice, strings lose expression and warmth of tone
-	Quick chromatic figures are not suitable for strings, and better for wood-wind
-	Wind instruments are of two classes: nasal and dark resonance (oboes and bassoons; bass: English horn and double bassoon); chest-voice and bright tone (flutes and clarinets; piccolo, bass flute, small clarinet, bass clarinet) 
-	Clarinet is the most expressive and subtle in nuance
    + Oboes and bassoons are also melodic instruments but more cantabile and peaceful
    + Quick passages often have doubled flutes, clarinets or strings
    + Note clarinets are not well adapted to sudden leaps in octave
-	Distinct and penetrating staccato passages are better suited to oboes and bassoons, while flutes and clarinets excel at well-sustained legato
-	Arpeggios and rapid alternation of intervals legato sound well on flutes and clarinets, but not oboes and bassoons
-	Upright piano is preferred over grand in orchestra
-	Celesta can supersede piano

Percussion Keyed Instruments

-	Kettle drums are the most important percussion in orchestra, capable of every dynamic shade from thundering fortissimo to barely perceptible  _pianissimo_
-	Brass instruments are not well adapted to expressive playing as woodwinds

Timbre Characteristics in Major/Minor, and Especial Suitability
 

-	Flute: Cold
    + Major: melodies of light and graceful character
    + Minor: slight touches of transient sorrow
-	Oboe
    + Major: artless and gay
    + Minor: pathetic and sad
-	Clarinet: Pliable and Expressive
    + Major: melodies of a joyful contemplative character/outbursts of mirth
    + Minor: sad and reflective melodies/impassioned and dramatic
-	Bassoon
    + Major: atmosphere of senile mockery
    + Minor: sad, ailing


In the extreme registers these instruments convey the following impressions to my mind:

Instrument | Low register | Very high register
--- | ---- | ----
Flute | Dull, cold |	Brilliant
Oboe | Wild	| Hard, dry
Clarinet | Ringing, threatening | Piercing
Bassoon | Sinister |	Tense

…although mood or frame of mind depends more upon the melody, harmony, rhythm and dynamic shades of expression. Nevertheless, melody can co-incide with the character of an instrument. For example:

-	 Melody of light character in tenor register (not for flutes, but bassoon with its mocking character to be light-hearted)
-	Sad, plaintive phrase in high soprano (not for bassoons, but flutes with their melancholy timbre to convey sorrow and distress)

Special Instruments

-	Piccolo has whistling, piercing quality which is extraordinarily powerful in its high compass; more than flute
-	Small clarinet likewise to clarinet
-	The small instruments’ low and middle range correspond to that of flute and clarinet but are much weaker and of little service
-	The following are often used as solo instruments/clearly exposed
    + Double bassoon’s deep notes are remarkably thick and dense in quality, very powerful in _piano_ passages
    + English horn/alto oboe is similar to oboe; listless, dreamy quality
    + Bass clarinet is of darker colour than clarinet in low register; incapable of joyful expression


Brass

-	Far less flexible than woodwinds
-	Brass heighten the effect of other orchestral groups by their powerful resonance
-	Trumpets, trombones and tubas are ~equal in strength
-	Horns in _forte_ passages are half as strong, but _piano_ they have the same weight as others played softly
-	Generally horns should be one degree stronger than rest of brass
-	Two _forte_ horns for one trumpet or trombone
-	Brass are similar in range and timbre
    + Generally they become more brilliant in the higher register
    +  _pp_ (_pianissimo_) the resonance is sweet, ff the tone is hard and crackling
    + Tone improves from  _sf_ to _p_
-	Trumpets are clear and penetrating in tone, stirring and rousing in _forte_ passages; in _piano_ phrases the high notes are full and silvery, low notes troubled (as though threatening danger); can execute rapid tremolando without difficulty
-	Horn is soft, poetical and full of beauty. Low it is dark and brilliant; high it is round and full. Middle notes resemble bassoon and the two instruments blend well together. For this reason, the horn serves as a link between the brass and wood-winds. 
-	Trombone is dark and threatening the deepest register, brilliant and triumphant in the higher. _Piano_ it is full but somewhat heavy, _forte_ it is powerful and sonorous. Typically fast passages are not played on trombone due to its special tone.
-	Tuba is thick and rough, less characteristic than trombone, but valuable for the strength and beauty of its low notes. Like the double bass and double bassoon, the tuba is eminently useful for doubling, an octave lower, the bass of the group to which it belongs. 
-	Stopped notes can only be employed on trumpets and horns (depends on construction); trumpet muted sounds better than stopped; in horns single notes are stopped in short phrases but muted in longer ones
-	Muted and stopped sound deadened, with a wild crackling character in _forte_, and tender and dull in _piano._ Resonance is greatly reduced, and timbre resembles oboe and English horn. Muted brass produces an effect of distance.

Plucked Instruments

-	Strings plucked (that is, _pizzicato_) sound like a new and independent group with its own quality of tone. Plucked instruments include strings, harp, guitar, zither and balalaika.
-	_Pizzicato_ playing has a small range of expression and is used chiefly as a colour effect.
-	Harp, like the string quartet, is more an instrument of colour than expression
    + Special function in execution of chords (strummed or fingered)
    + Accompanying instrument
    + _Glissando_ can only be used in upper octave, quite _piano_, where the sound of strings is sufficiently clear, yet not too prolonged. 
    + Tender poetic quality that is adapted to every dynamic shade, but not a very powerful instrument
    + Harmonic notes have great charm but little resonance, and are only possible played quite softly


Resonance (to be continued from p33)
